apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: telegraf
  region: us-west-1
  version: "1.18"

nodeGroups:
  - name: ng-1
    instanceType: r5.2xlarge
    minSize: 1
    desiredCapacity: 3
    maxSize: 3
    availabilityZones: ["us-west-1a"]
