apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

nodeGroups:
  - name: ng-1
    instanceType: r5.2xlarge
    minSize: 1
    desiredCapacity: 3
    maxSize: 6
    availabilityZones: ["us-east-1a","us-east-1b","us-east-1c"]
